version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: lingopulse_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      # Make sure to point Ollama URL to host machine so Docker container can access it
      - OLLAMA_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
